version: '3.4'

networks:
  alert:
    driver: bridge
    
services:
  gateway:
    container_name: Alert.Gateway
    build:
      context: .
      dockerfile: NotificationGateway/NotificationGateway.Web/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq
      - database
    networks:
      - alert

  email:
    container_name: Alert.EmailNotifier
    build:
      context: .
      dockerfile: EmailNotifier/EmailNotifier.Web/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - gateway
    networks:
      - alert

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - alert

  database:
    container_name: PostgreSQL
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: "Alert"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - 'C:/Backups/Alert:/var/lib/postgresql/data'
    networks:
      - alert
  
volumes:
  postgres-data: